# Generated by Django 2.0.2 on 2018-04-05 07:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='defaultprivacy',
            table='default_privacy',
        ),
    ]
