# Generated by Django 2.0.2 on 2018-04-09 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0002_auto_20180407_2141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='follow',
            name='updated',
            field=models.DateTimeField(editable=False),
        ),
    ]
