# Generated by Django 2.0.2 on 2018-04-09 02:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='challenge',
            name='impostor_level',
            field=models.IntegerField(choices=[(0, 'Shadow'), (1, 'Looming'), (2, 'Consumed'), (3, 'Meltdown')], default=0, verbose_name='Impostor Level'),
        ),
        migrations.AlterField(
            model_name='challenge',
            name='updated',
            field=models.DateTimeField(editable=False),
        ),
        migrations.AlterField(
            model_name='challenge',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='challenges', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='empathy',
            name='updated',
            field=models.DateTimeField(editable=False),
        ),
    ]
