# Generated by Django 2.0.2 on 2018-04-09 05:10

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('challenges', '0002_auto_20180409_0257'),
    ]

    operations = [
        migrations.RenameField(
            model_name='empathy',
            old_name='user',
            new_name='empathizing_user',
        ),
        migrations.AlterUniqueTogether(
            name='empathy',
            unique_together={('empathizing_user', 'challenge')},
        ),
    ]
