# Generated by Django 2.0.2 on 2018-04-09 04:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import root.base_models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Accomplishment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(editable=False)),
                ('updated', models.DateTimeField(editable=False)),
                ('title', models.CharField(max_length=140)),
                ('notes', models.TextField(blank=True)),
                ('privacy', models.IntegerField(choices=[(-1, 'private'), (0, 'anonymous'), (1, 'public')], default=root.base_models.Privacy(-1), verbose_name='Privacy Setting')),
                ('accomplishment_level', models.IntegerField(choices=[(0, 'Stepping stone'), (1, 'Milestone'), (2, 'Eventful'), (3, 'Life changing'), (4, 'I am become Wizard')], default=0, verbose_name='Accomplishment Level')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accomplishments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'accomplishments',
            },
        ),
        migrations.CreateModel(
            name='Inspiration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(editable=False)),
                ('updated', models.DateTimeField(editable=False)),
                ('accomplishment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inspired_users', to='accomplishments.Accomplishment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inspiring_accomplishments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'inspiration',
            },
        ),
    ]
