# Generated by Django 2.0.2 on 2018-04-09 05:10

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accomplishments', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inspiration',
            old_name='user',
            new_name='inspired_user',
        ),
        migrations.AlterUniqueTogether(
            name='inspiration',
            unique_together={('inspired_user', 'accomplishment')},
        ),
    ]
