# Generated by Django 2.0.2 on 2018-04-09 08:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accomplishments', '0002_auto_20180409_0510'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inspiration',
            name='inspired_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inspirations', to=settings.AUTH_USER_MODEL),
        ),
    ]
